# Generated by Django 3.2.5 on 2024-07-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contect',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contect',
            new_name='content',
        ),
    ]
